server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router(SPA) 새로고침 처리를 위한 설정
        try_files $uri $uri/ /index.html;
    }
}