name: Dev CD Pipeline (Frontend)

on:
  workflow_run:
    workflows: ["Frontend CI Pipeline"]
    types:
      - completed
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-openstack:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: 'TEAM-SEED-PLUS/SEED-PLUS-INFRA'
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: 'infra-repo'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OPENSTACK_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2224 -H ${{ secrets.TARGET_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          cd infra-repo/openstack-cd
          ansible-playbook -i ${{ secrets.TARGET_IP }}:2224, -u ubuntu playbooks/os_dev_deploy.yml \
            --extra-vars "target_app=frontend \
                          ecr_registry=${{ secrets.ECR_REGISTRY }} \
                          ecr_repository=${{ secrets.ECR_REPOSITORY }} \
                          image_tag=${{ github.event.workflow_run.head_sha || github.sha }} \
                          aws_region=ap-northeast-2 \
                          aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }} \
                          aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }} \
                          aws_session_token=${{ env.AWS_SESSION_TOKEN }}"
